# Generated by Django 6.0.6 on 2026-07-13 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_ownerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='delete_password_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
