# Generated by Django 6.0.6 on 2026-07-13 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_review_delete_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewreply',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='maps.review'),
        ),
    ]
