PLACES = [
    {
        'id': 'gyeongbokgung',
        'name': '경복궁',
        'category': '역사 명소',
        'lat': 37.579617,
        'lng': 126.977041,
        'rating': 4.6,
        'reviews': '리뷰 98,000+',
        'address': '서울특별시 종로구 사직로 161',
        'hours': '09:00-18:00, 화요일 휴무',
        'tip': '광화문에서 시작해 국립고궁박물관까지 함께 둘러보기 좋습니다.',
        'description': '조선 왕조의 중심 궁궐로, 넓은 전각과 북악산 풍경이 이어지는 서울 대표 역사 공간입니다.',
        'source': 'Korea Heritage Service / public coordinate references',
    },
    {
        'id': 'n-seoul-tower',
        'name': 'N서울타워',
        'category': '전망대',
        'lat': 37.551417,
        'lng': 126.987972,
        'rating': 4.4,
        'reviews': '리뷰 62,000+',
        'address': '서울특별시 용산구 남산공원길 105',
        'hours': '10:30-22:30',
        'tip': '해질녘에 올라가면 도심 야경까지 자연스럽게 이어집니다.',
        'description': '남산 정상에 있는 서울의 대표 전망 명소로, 한강과 도심 스카이라인을 한눈에 볼 수 있습니다.',
        'source': 'public coordinate references',
    },
    {
        'id': 'dongdaemun-design-plaza',
        'name': '동대문디자인플라자',
        'category': '문화 공간',
        'lat': 37.566525,
        'lng': 127.009224,
        'rating': 4.3,
        'reviews': '리뷰 47,000+',
        'address': '서울특별시 중구 을지로 281',
        'hours': '10:00-20:00',
        'tip': '전시 일정과 야간 외관 조명을 함께 확인하면 좋습니다.',
        'description': '곡선형 건축물과 전시, 디자인 마켓이 모인 동대문 중심의 복합 문화 공간입니다.',
        'source': 'Visit Seoul / public coordinate references',
    },
    {
        'id': 'seoul-forest',
        'name': '서울숲',
        'category': '도시 공원',
        'lat': 37.544625,
        'lng': 127.039844,
        'rating': 4.6,
        'reviews': '리뷰 31,000+',
        'address': '서울특별시 성동구 뚝섬로 273',
        'hours': '상시 개방',
        'tip': '성수동 카페 거리와 묶어 걷기 좋은 코스입니다.',
        'description': '숲길, 잔디마당, 생태 공간이 이어지는 넓은 도심 공원입니다.',
        'source': 'Seoul Metropolitan Government / public coordinate references',
    },
    {
        'id': 'starfield-coex-mall',
        'name': '스타필드 코엑스몰',
        'category': '쇼핑몰',
        'lat': 37.511805,
        'lng': 127.059159,
        'rating': 4.4,
        'reviews': '리뷰 54,000+',
        'address': '서울특별시 강남구 영동대로 513',
        'hours': '10:30-22:00',
        'tip': '별마당도서관과 봉은사를 함께 방문하기 편합니다.',
        'description': '강남 삼성동에 있는 대형 복합 쇼핑 공간으로, 쇼핑과 식당, 전시 시설이 밀집해 있습니다.',
        'source': 'Starfield / public coordinate references',
    },
    {
        'id': 'lotte-world-tower',
        'name': '롯데월드타워',
        'category': '랜드마크',
        'lat': 37.512218,
        'lng': 127.102707,
        'rating': 4.5,
        'reviews': '리뷰 73,000+',
        'address': '서울특별시 송파구 올림픽로 300',
        'hours': '10:30-22:00',
        'tip': '석촌호수 산책과 서울스카이 전망대를 함께 즐기기 좋습니다.',
        'description': '잠실에 위치한 초고층 랜드마크로, 쇼핑몰과 전망대, 식음 공간이 연결되어 있습니다.',
        'source': 'Lotte World Tower / public coordinate references',
    },
]
